// قائمة أكواد الدول (اختصار الدولة، اسم الدولة، كود الاتصال الدولي)
export const countryCodes = [
  { code: '+20', name: 'Egypt', iso: 'EG', flag: '🇪🇬' },
  { code: '+966', name: 'Saudi Arabia', iso: 'SA', flag: '🇸🇦' },
  { code: '+971', name: 'UAE', iso: 'AE', flag: '🇦🇪' },
  { code: '+1', name: 'United States', iso: 'US', flag: '🇺🇸' },
  { code: '+44', name: 'United Kingdom', iso: 'GB', flag: '🇬🇧' },
  { code: '+49', name: 'Germany', iso: 'DE', flag: '🇩🇪' },
  { code: '+33', name: 'France', iso: 'FR', flag: '🇫🇷' },
  { code: '+34', name: 'Spain', iso: 'ES', flag: '🇪🇸' },
  { code: '+39', name: 'Italy', iso: 'IT', flag: '🇮🇹' },
  { code: '+55', name: 'Brazil', iso: 'BR', flag: '🇧🇷' },
  { code: '+90', name: 'Turkey', iso: 'TR', flag: '🇹🇷' },
  { code: '+7', name: 'Russia', iso: 'RU', flag: '🇷🇺' },
  { code: '+81', name: 'Japan', iso: 'JP', flag: '🇯🇵' },
  { code: '+86', name: 'China', iso: 'CN', flag: '🇨🇳' },
  { code: '+91', name: 'India', iso: 'IN', flag: '🇮🇳' },
  { code: '+61', name: 'Australia', iso: 'AU', flag: '🇦🇺' },
  { code: '+974', name: 'Qatar', iso: 'QA', flag: '🇶🇦' },
  { code: '+965', name: 'Kuwait', iso: 'KW', flag: '🇰🇼' },
  { code: '+962', name: 'Jordan', iso: 'JO', flag: '🇯🇴' },
  { code: '+963', name: 'Syria', iso: 'SY', flag: '🇸🇾' },
  { code: '+964', name: 'Iraq', iso: 'IQ', flag: '🇮🇶' },
  { code: '+218', name: 'Libya', iso: 'LY', flag: '🇱🇾' },
  { code: '+212', name: 'Morocco', iso: 'MA', flag: '🇲🇦' },
  { code: '+216', name: 'Tunisia', iso: 'TN', flag: '🇹🇳' },
  { code: '+213', name: 'Algeria', iso: 'DZ', flag: '🇩🇿' },
  { code: '+249', name: 'Sudan', iso: 'SD', flag: '🇸🇩' },
  { code: '+27', name: 'South Africa', iso: 'ZA', flag: '🇿🇦' },
  // ... يمكنك إضافة باقي الدول حسب الحاجة
];
