import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'es' | 'pt' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations = {
  en: {
    'footer.popularDestinations': 'Popular Destinations',
    'nav.destinations': 'Destinations',
    'nav.packages': 'Packages',
    'nav.experiences': 'Experiences',
    'nav.tripbuilder': 'Trip Builder',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'hero.title': 'Discover Egypt Like Never Before',
    'hero.subtitle': 'Immerse yourself in the timeless wonders of ancient Egypt with our curated luxury experiences',
    'hero.cta': 'Start Your Journey',
    'hero.exploreDestinations': 'Explore Destinations',
    'hero.stats.destinations': 'Unique Destinations',
    'hero.stats.travelers': 'Happy Travelers',
    'hero.stats.experiences': 'Cultural Experiences',
    'destinations.title': 'Top Destinations',
    'destinations.subtitle': 'Explore Egypt\'s most captivating locations',
    'destinations.seeAll': 'See All Destinations',
    'packages.title': 'Popular Packages',
    'packages.subtitle': 'Carefully crafted journeys for every traveler',
    'packages.viewAll': 'View All Packages',
    'packages.heading': 'Travel Packages',
    'packages.description': 'Discover our carefully curated travel packages designed to showcase the best of Egypt.',
    'experiences.title': 'Cultural Experiences',
    'experiences.subtitle': 'Authentic encounters with Egyptian heritage',
    'experiences.exploreAll': 'Explore All Experiences',
    'why.title': 'Why Choose Egypt?',
    'whyEgypt.title': 'Why Egypt?',
    'testimonials.title': 'Traveler Stories',
    'testimonials.heading': 'Traveler Stories',
    'newsletter.title': 'Stay Updated',
    'newsletter.subtitle': 'Get exclusive travel insights and special offers',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.subscribe': 'Subscribe',
    // Package Details
    'package.loading': 'Loading package details...',
    'package.notfound': 'Package Not Found',
    'package.back': 'Back',
    'package.highlights': 'Highlights',
    'package.cancellationPolicyTitle': 'Cancellation Policy',
    'package.cancellationPolicy': 'You can cancel free of charge up to 24 hours before the trip.',
    'package.bookNow': 'Book Now',
    'package.success': 'Booking request sent successfully! We will contact you soon.',
    'package.fullName': 'Full Name',
    'package.fullNamePlaceholder': 'Enter your full name',
    'package.email': 'Email',
    'package.emailPlaceholder': 'example@email.com',
    'package.phone': 'Phone Number',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Trip Date',
    'package.datePlaceholder': 'Select trip date',
    'package.people': 'Number of People',
    'package.peoplePlaceholder': 'Enter number of people',
    'package.submit': 'Submit Booking',
    // Experiences Page
    'experiences.notfound': 'No experiences found.',
    'error.loading': 'Error loading experiences',
    // Destination Details
    'destination.loading': 'Loading destination details...',
    'destination.notfound': 'Destination Not Found',
    'destination.back': 'Back',
    'destination.highlights': 'Highlights',
    // Experiences Details
    'experience.loading': 'Loading experience details...',
    'experience.notfound': 'Experience Not Found',
    'experience.back': 'Back',
    'experience.highlights': 'Highlights',
    'header.brand': 'Egyptian Dreams',
    'header.english': 'English',
    'header.spanish': 'Spanish',
    'header.portuguese': 'Portuguese',
    'header.German': 'German',
    'footer.company': 'Company',
    'footer.privacy': 'Privacy Policy',
    'footer.description': "Creating unforgettable journeys through Egypt's timeless wonders. Experience authentic Egyptian culture with our expert local guides.",
    'footer.rights': '© 2025 Egyptian Dreams. All rights reserved.',
    'footer.followUs': 'Follow us:',
    'footer.dahab': 'Dahab',
    'footer.siwa': 'Siwa Oasis',
    'footer.luxor': 'Luxor',
    'footer.whiteDesert': 'White Desert',
    'footer.safari': 'Desert Safari',
    'footer.diving': 'Diving Tours',
    'footer.culture': 'Cultural Immersion',
    'footer.photo': 'Photography Tours',
    'destinations.description': "From ancient wonders to pristine beaches, explore the most captivating destinations Egypt has to offer.",
    'destinations.activities': 'Activities',
    'destinations.highlights': 'Highlights',
    'whyEgypt.benefit1.title': 'Rich Heritage',
    'whyEgypt.benefit1.desc': 'Explore 5,000 years of fascinating history and ancient civilization',
    'whyEgypt.benefit2.title': 'Diverse Landscapes',
    'whyEgypt.benefit2.desc': 'From Red Sea reefs to Sahara dunes and Nile valleys',
    'whyEgypt.benefit3.title': 'Warm Hospitality',
    'whyEgypt.benefit3.desc': 'Experience genuine Egyptian warmth and traditional welcome',
    'whyEgypt.benefit4.title': 'Safe Travel',
    'whyEgypt.benefit4.desc': 'Well-established tourism infrastructure with experienced guides',
    'whyEgypt.benefit5.title': 'Great Value',
    'whyEgypt.benefit5.desc': 'Affordable luxury experiences and exceptional value for money',
    'whyEgypt.benefit6.title': 'Local Expertise',
    'whyEgypt.benefit6.desc': 'Native guides sharing authentic stories and hidden gems',
    'whyEgypt.subtitle': 'Uncover the unique reasons to visit Egypt and make your journey unforgettable.',
    'newsletter.nospam': 'No spam, just the best tips and exclusive offers.',
    'testimonials.subtitle': 'See what our travelers have to say about their Egyptian adventures.',
    'hero.ctaSubtitle': 'Start your adventure with us and discover the best of Egypt!',
    'about.title': 'About Egyptian Dreams',
    'about.subtitle': 'Our story, mission, and the passionate team behind your Egyptian adventures',
    'about.visionTitle': 'Our Vision & Mission',
    'about.vision': 'To connect the world with the magic of Egypt through exceptional, authentic travel experiences.',
    'about.mission': 'We are dedicated to making every journey personal, safe, and unforgettable.',
    'about.teamTitle': 'Meet Our Team',
    'about.valuesTitle': 'Our Values',
    'about.value1.title': 'Authenticity',
    'about.value1.desc': 'We provide genuine Egyptian experiences.',
    'about.value2.title': 'Expertise',
    'about.value2.desc': 'Our team consists of local experts and passionate guides.',
    'about.value3.title': 'Safety',
    'about.value3.desc': 'Your safety and comfort are our top priorities.',
    'about.value4.title': 'Sustainability',
    'about.value4.desc': 'We care for Egypt’s heritage and environment.',
    'about.closing': 'Join us and let’s create your dream Egyptian adventure!',
  },
  es: {
     'footer.popularDestinations': 'Destinos Populares',
    'nav.destinations': 'Destinos',
    'nav.packages': 'Paquetes',
    'nav.experiences': 'Experiencias',
    'nav.tripbuilder': 'Planificador',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.blog': 'Blog',
    'hero.title': 'Descubre Egipto Como Nunca Antes',
    'hero.subtitle': 'Sumérgete en las maravillas eternas del antiguo Egipto con nuestras experiencias de lujo',
    'hero.cta': 'Comienza Tu Viaje',
    'hero.exploreDestinations': 'Explorar Destinos',
    'hero.stats.destinations': 'Destinos Únicos',
    'hero.stats.travelers': 'Viajeros Felices',
    'hero.stats.experiences': 'Experiencias Culturales',
    'destinations.title': 'Principales Destinos',
    'destinations.subtitle': 'Explora los lugares más cautivadores de Egipto',
    'destinations.seeAll': 'Ver Todos los Destinos',
    'packages.title': 'Paquetes Populares',
    'packages.subtitle': 'Viajes cuidadosamente diseñados para cada viajero',
    'packages.viewAll': 'Ver Todos los Paquetes',
    'packages.heading': 'Paquetes de Viaje',
    'packages.description': 'Descubre nuestros paquetes de viaje cuidadosamente seleccionados para mostrar lo mejor de Egipto.',
    'experiences.title': 'Experiencias Culturales',
    'experiences.subtitle': 'Encuentros auténticos con el patrimonio egipcio',
    'experiences.exploreAll': 'Explorar Todas las Experiencias',
    'why.title': '¿Por Qué Elegir Egipto?',
    'whyEgypt.title': '¿Por Qué Egipto?',
    'testimonials.title': 'Historias de Viajeros',
    'testimonials.heading': 'Historias de Viajeros',
    'newsletter.title': 'Mantente Actualizado',
    'newsletter.subtitle': 'Recibe información exclusiva de viajes y ofertas especiales',
    'newsletter.placeholder': 'Ingresa tu email',
    'newsletter.subscribe': 'Suscribirse',
    // Package Details
    'package.loading': 'Cargando detalles del paquete...',
    'package.notfound': 'Paquete no encontrado',
    'package.back': 'Atrás',
    'package.highlights': 'Aspectos destacados',
    'package.cancellationPolicyTitle': 'Política de cancelación',
    'package.cancellationPolicy': 'Puedes cancelar gratis hasta 24 horas antes del viaje.',
    'package.bookNow': 'Reservar ahora',
    'package.success': '¡Solicitud de reserva enviada con éxito! Nos pondremos en contacto contigo pronto.',
    'package.fullName': 'Nombre completo',
    'package.fullNamePlaceholder': 'Introduce tu nombre completo',
    'package.email': 'Correo electrónico',
    'package.emailPlaceholder': 'example@email.com',
    'package.phone': 'Número de teléfono',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Fecha del viaje',
    'package.datePlaceholder': 'Selecciona la fecha del viaje',
    'package.people': 'Número de personas',
    'package.peoplePlaceholder': 'Introduce el número de personas',
    'package.submit': 'Enviar reserva',
    // Experiences Page
    'experiences.notfound': 'No se encontraron experiencias.',
    'error.loading': 'Error al cargar experiencias',
    // Destination Details
    'destination.loading': 'Cargando detalles del destino...',
    'destination.notfound': 'Destino no encontrado',
    'destination.back': 'Atrás',
    'destination.highlights': 'Aspectos destacados',
    // Experiences Details
    'experience.loading': 'Cargando detalles de la experiencia...',
    'experience.notfound': 'Experiencia no encontrada',
    'experience.back': 'Atrás',
    'experience.highlights': 'Aspectos destacados',
    'header.brand': 'Sueños Egipcios',
    'header.english': 'Inglés',
    'header.spanish': 'Español',
    'header.portuguese': 'Portugués',
    'header.German': 'German',
    'footer.company': 'Compañía',
    'footer.privacy': 'Política de Privacidad',
    'footer.description': 'Creamos viajes inolvidables a través de las maravilhas eternas de Egipto. Vive la cultura egipcia auténtica con nuestros guías locales expertos.',
    'footer.rights': '© 2025 Sueños Egipcios. Todos los derechos reservados.',
    'footer.followUs': 'Síguenos:',
    'footer.dahab': 'Dahab',
    'footer.siwa': 'Oasis de Siwa',
    'footer.luxor': 'Luxor',
    'footer.whiteDesert': 'Desierto Blanco',
    'footer.safari': 'Safari por el desierto',
    'footer.diving': 'Tours de buceo',
    'footer.culture': 'Inmersión cultural',
    'footer.photo': 'Tours fotográficos',
    'destinations.description': 'Desde maravillas antiguas hasta playas vírgenes, explora los destinos más cautivantes que Egipto tiene para ofrecer.',
    'destinations.activities': 'Actividades',
    'destinations.highlights': 'Aspectos destacados',
    'whyEgypt.benefit1.title': 'Rica Herencia',
    'whyEgypt.benefit1.desc': 'Explora 5,000 años de fascinante historia y civilización antigua',
    'whyEgypt.benefit2.title': 'Paisagens Diversos',
    'whyEgypt.benefit2.desc': 'Desde los arrecifes del Mar Rojo hasta las dunas del Sahara y los valles del Nilo',
    'whyEgypt.benefit3.title': 'Hospitalidad Cálida',
    'whyEgypt.benefit3.desc': 'Experimente o calor genuíno egípcio e as boas-vindas tradicionais',
    'whyEgypt.benefit4.title': 'Viagem Segura',
    'whyEgypt.benefit4.desc': 'Infraestrutura turística consolidada com guias experientes',
    'whyEgypt.benefit5.title': 'Gran Valor',
    'whyEgypt.benefit5.desc': 'Experiências de luxo acessíveis e valor excepcional',
    'whyEgypt.benefit6.title': 'Experiencia Local',
    'whyEgypt.benefit6.desc': 'Guías nativos que compartilham histórias autênticas e segredos ocultos',
    'whyEgypt.subtitle': 'Descubre las razones únicas para visitar Egipto e haz tu viaje inolvidable.',
    'newsletter.nospam': 'Sin spam, solo los mejores consejos y ofertas exclusivas.',
    'testimonials.subtitle': 'Descubre lo que dicen nuestros viajeros sobre sus aventuras en Egipto.',
    'hero.ctaSubtitle': '¡Comienza tu aventura con nosotros y descubre lo mejor de Egipto!',
    'about.title': 'Sobre Egyptian Dreams',
    'about.subtitle': 'Nuestra historia, misión y el equipo apasionado detrás de tus aventuras en Egipto',
    'about.visionTitle': 'Nuestra Visión y Misión',
    'about.vision': 'Conectar al mundo con la magia de Egipto a través de experiencias auténticas y excepcionales.',
    'about.mission': 'Nos dedicamos a hacer que cada viaje sea personal, seguro e inolvidable.',
    'about.teamTitle': 'Conoce a Nuestro Equipo',
    'about.valuesTitle': 'Nuestros Valores',
    'about.value1.title': 'Autenticidad',
    'about.value1.desc': 'Ofrecemos experiencias egipcias genuinas.',
    'about.value2.title': 'Experiencia',
    'about.value2.desc': 'Nuestro equipo está formado por expertos locales y guías apasionados.',
    'about.value3.title': 'Seguridad',
    'about.value3.desc': 'Tu seguridad y comodidad son nuestra prioridad.',
    'about.value4.title': 'Sostenibilidad',
    'about.value4.desc': 'Cuidamos el patrimonio y el medio ambiente de Egipto.',
    'about.closing': '¡Únete a nosotros y creemos juntos tu aventura soñada en Egipto!',
  },
  pt: {
     'footer.popularDestinations': 'Destinos Populares',
    'nav.destinations': 'Destinos',
    'nav.packages': 'Pacotes',
    'nav.experiences': 'Experiências',
    'nav.tripbuilder': 'Planejador',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.blog': 'Blog',
    'header.english': 'Inglês',
    'header.spanish': 'Espanhol',
    'header.portuguese': 'Português',
    'header.german': 'Alemão',
    'hero.title': 'Descubra o Egito Como Nunca Antes',
    'hero.subtitle': 'Mergulhe nas maravilhas eternas do antigo Egito com nossas experiências de luxo',
    'hero.cta': 'Comece Sua Jornada',
    'hero.exploreDestinations': 'Explorar Destinos',
    'hero.stats.destinations': 'Destinos Únicos',
    'hero.stats.travelers': 'Viajantes Felizes',
    'hero.stats.experiences': 'Experiências Culturais',
    'destinations.title': 'Principais Destinos',
    'destinations.subtitle': 'Explore os locais mais cativantes do Egito',
    'destinations.seeAll': 'Ver Todos os Destinos',
    'packages.title': 'Pacotes Populares',
    'packages.subtitle': 'Viagens cuidadosamente criadas para cada viajante',
    'packages.viewAll': 'Ver Todos os Pacotes',
    'packages.heading': 'Pacotes de Viagem',
    'packages.description': 'Descubra nossos pacotes de viagem cuidadosamente selecionados para mostrar o melhor do Egito.',
    'experiences.title': 'Experiências Culturais',
    'experiences.subtitle': 'Encontros autênticos com o patrimônio egípcio',
    'experiences.exploreAll': 'Explorar Todas as Experiências',
    'why.title': 'Por Que Escolher o Egito?',
    'whyEgypt.title': 'Por Que o Egito?',
    'testimonials.title': 'Histórias de Viajantes',
    'testimonials.heading': 'Histórias de Viajantes',
    'newsletter.title': 'Mantenha-se Atualizado',
    'newsletter.subtitle': 'Receba informações exclusivas de viagem e ofertas especiais',
    'newsletter.placeholder': 'Digite seu email',
    'newsletter.subscribe': 'Assinar',
    'newsletter.stayConnected': 'Fique Conectado',
    'newsletter.nospam': 'Sem spam, apenas as melhores dicas e ofertas exclusivas.',
 
    'footer.experiences': 'Experiências',
    'footer.company': 'Empresa',
    'footer.privacy': 'Política de Privacidade',
    'footer.description': 'Criando viagens inesquecíveis pelas maravilhas eternas do Egito. Viva a cultura egípcia autêntica com nossos guias locais especialistas.',
    'footer.rights': '© 2025 Egyptian Dreams. Todos os direitos reservados.',
    'footer.followUs': 'Siga-nos:',
    'footer.dahab': 'Dahab',
    'footer.siwa': 'Oásis de Siuá',
    'footer.luxor': 'Luxor',
    'footer.whiteDesert': 'Deserto Branco',
    'footer.safari': 'Safari no deserto',
    'footer.diving': 'Passeios de mergulho',
    'footer.culture': 'Imersão cultural',
    'footer.photo': 'Passeios fotográficos',
    // Package Details
    'package.loading': 'Paketdetails werden geladen...',
    'package.notfound': 'Paket nicht gefunden',
    'package.back': 'Zurück',
    'package.highlights': 'Highlights',
    'package.cancellationPolicyTitle': 'Stornierungsbedingungen',
    'package.cancellationPolicy': 'Kostenlose Stornierung bis 24 Stunden vor Reiseantritt.',
    'package.bookNow': 'Jetzt buchen',
    'package.success': 'Buchungsanfrage erfolgreich gesendet! Wir kontaktieren dich in Kürze.',
    'package.fullName': 'Vollständiger Name',
    'package.fullNamePlaceholder': 'Gib deinen vollständigen Namen ein',
    'package.email': 'E-Mail',
    'package.emailPlaceholder': 'beispiel@email.com',
    'package.phone': 'Telefonnummer',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Reisedatum',
    'package.datePlaceholder': 'Reisedatum auswählen',
    'package.people': 'Anzahl der Personen',
    'package.peoplePlaceholder': 'Anzahl der Personen eingeben',
    'package.submit': 'Buchung absenden',
    // Experiences Page
    'experiences.notfound': 'Keine Erlebnisse gefunden.',
    'error.loading': 'Fehler beim Laden der Erlebnisse',
    // Destination Details
    'destination.loading': 'Reisezieldetails werden geladen...',
    'destination.notfound': 'Reiseziel nicht gefunden',
    'destination.back': 'Zurück',
    'destination.highlights': 'Highlights',
    // Experiences Details
    'experience.loading': 'Erlebnisdetails werden geladen...',
    'experience.notfound': 'Erlebnis nicht gefunden',
    'experience.back': 'Zurück',
    'experience.highlights': 'Highlights',
   
  },
    de: {
    'footer.popularDestinations': 'Beliebte Reiseziele',
    'nav.destinations': 'Reiseziele',
    'nav.packages': 'Pakete',
    'nav.experiences': 'Erlebnisse',
    'nav.tripbuilder': 'Reiseplaner',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.blog': 'Blog',
     'header.english': 'Inglês',
    'header.spanish': 'Espanhol',
    'header.portuguese': 'Português',
    'header.german': 'Alemão',
    'hero.title': 'Entdecke Ägypten wie nie zuvor',
    'hero.subtitle': 'Tauche ein in die zeitlosen Wunder des alten Ägypten mit unseren kuratierten Luxus-Erlebnissen',
    'hero.cta': 'Beginne deine Reise',
    'hero.exploreDestinations': 'Entdecke Reiseziele',
    'hero.stats.destinations': 'Einzigartige Reiseziele',
    'hero.stats.travelers': 'Zufriedene Reisende',
    'hero.stats.experiences': 'Kulturelle Erlebnisse',
    'destinations.title': 'Top Reiseziele',
    'destinations.subtitle': 'Entdecke die faszinierendsten Orte Ägyptens',
    'destinations.seeAll': 'Alle Reiseziele anzeigen',
    'packages.title': 'Beliebte Pakete',
    'packages.subtitle': 'Sorgfältig gestaltete Reisen für jeden Reisenden',
    'packages.viewAll': 'Alle Pakete anzeigen',
    'packages.heading': 'Reise-Pakete',
    'packages.description': 'Entdecke unsere sorgfältig kuratierten Reisepakete, die das Beste Ägyptens präsentieren.',
    'experiences.title': 'Kulturelle Erlebnisse',
    'experiences.subtitle': 'Authentische Begegnungen mit dem ägyptischen Erbe',
    'experiences.exploreAll': 'Alle Erlebnisse entdecken',
    'why.title': 'Warum Ägypten wählen?',
    'whyEgypt.title': 'Warum Ägypten?',
    'testimonials.title': 'Reiseberichte',
    'testimonials.heading': 'Reiseberichte',
    'newsletter.title': 'Bleiben Sie auf dem Laufenden',
    'newsletter.subtitle': 'Erhalten Sie exklusive Reiseeinblicke und Sonderangebote',
    'newsletter.placeholder': 'Geben Sie Ihre E-Mail ein',
    'newsletter.subscribe': 'Abonnieren',
    // Package Details
    'package.loading': 'Lade Paketdetails...',
    'package.notfound': 'Paket nicht gefunden',
    'package.back': 'Zurück',
    'package.highlights': 'Highlights',
    'package.cancellationPolicyTitle': 'Stornierungsbedingungen',
    'package.cancellationPolicy': 'Sie können bis zu 24 Stunden vor der Reise kostenlos stornieren.',
    'package.bookNow': 'Jetzt buchen',
    'package.success': 'Buchungsanfrage erfolgreich gesendet! Wir werden Sie bald kontaktieren.',
    'package.fullName': 'Vollständiger Name',
    'package.fullNamePlaceholder': 'Geben Sie Ihren vollständigen Namen ein',
    'package.email': '-Mail',
    'package.emailPlaceholder': 'beispiel@email.com',
    'package.phone': 'Telefonnummer',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Reisedatum',
    'package.datePlaceholder': 'Reisedatum auswählen',
    'package.people': 'Anzahl der Personen',
    'package.peoplePlaceholder': 'Anzahl der Personen eingeben',
    'package.submit': 'Buchung absenden',
    // Experiences Page
    'experiences.notfound': 'Keine Erlebnisse gefunden.',
    'error.loading': 'Fehler beim Laden der Erlebnisse',
    // Destination Details
    'destination.loading': 'Lade Zielortdetails...',
    'destination.notfound': 'Zielort nicht gefunden',
    'destination.back': 'Zurück',
    'destination.highlights': 'Highlights',
    // Experiences Details
    'experience.loading': 'Lade Erlebnisdetails...',
    'experience.notfound': 'Erlebnis nicht gefunden',
    'experience.back': 'Zurück',
    'experience.highlights': 'Highlights',
    'header.brand': 'Egyptian Dreams',
    'header.english': 'English',
    'header.spanish': 'Spanisch',
    'header.portuguese': 'Portugiesisch',
    'header.german': 'Deutsch',
    'footer.company': 'Unternehmen',
    'footer.privacy': 'Datenschutz-Bestimmungen',
    'footer.description': "Creating unforgettable journeys through Egypt's timeless wonders. Experience authentic Egyptian culture with our expert local guides.",
    'footer.rights': '© 2025 Egyptian Dreams. All rights reserved.',
    'footer.followUs': 'Follow us:',
    'footer.dahab': 'Dahab',
    'footer.siwa': 'Siwa Oasis',
    'footer.luxor': 'Luxor',
    'footer.whiteDesert': 'White Desert',
    'footer.safari': 'Desert Safari',
    'footer.diving': 'Diving Tours',
    'footer.culture': 'Cultural Immersion',
    'footer.photo': 'Photography Tours',
    'destinations.description': "From ancient wonders to pristine beaches, explore the most captivating destinations Egypt has to offer.",
    'destinations.activities': 'Activities',
    'destinations.highlights': 'Highlights',
    'whyEgypt.benefit1.title': 'Rich Heritage',
    'whyEgypt.benefit1.desc': 'Explore 5,000 years of fascinating history and ancient civilization',
    'whyEgypt.benefit2.title': 'Diverse Landscapes',
    'whyEgypt.benefit2.desc': 'From Red Sea reefs to Sahara dunes and Nile valleys',
    'whyEgypt.benefit3.title': 'Warm Hospitality',
    'whyEgypt.benefit3.desc': 'Experience genuine Egyptian warmth and traditional welcome',
    'whyEgypt.benefit4.title': 'Safe Travel',
    'whyEgypt.benefit4.desc': 'Well-established tourism infrastructure with experienced guides',
    'whyEgypt.benefit5.title': 'Great Value',
    'whyEgypt.benefit5.desc': 'Affordable luxury experiences and exceptional value for money',
    'whyEgypt.benefit6.title': 'Local Expertise',
    'whyEgypt.benefit6.desc': 'Native guides sharing authentic stories and hidden gems',
    'whyEgypt.subtitle': 'Uncover the unique reasons to visit Egypt and make your journey unforgettable.',
    'newsletter.nospam': 'No spam, just the best tips and exclusive offers.',
    'testimonials.subtitle': 'See what our travelers have to say about their Egyptian adventures.',
    'hero.ctaSubtitle': 'Start your adventure with us and discover the best of Egypt!',
    'about.title': 'About Egyptian Dreams',
    'about.subtitle': 'Our story, mission, and the passionate team behind your Egyptian adventures',
    'about.visionTitle': 'Our Vision & Mission',
    'about.vision': 'To connect the world with the magic of Egypt through exceptional, authentic travel experiences.',
    'about.mission': 'We are dedicated to making every journey personal, safe, and unforgettable.',
    'about.teamTitle': 'Meet Our Team',
    'about.valuesTitle': 'Our Values',
    'about.value1.title': 'Authenticity',
    'about.value1.desc': 'We provide genuine Egyptian experiences.',
    'about.value2.title': 'Expertise',
    'about.value2.desc': 'Our team consists of local experts and passionate guides.',
    'about.value3.title': 'Safety',
    'about.value3.desc': 'Your safety and comfort are our top priorities.',
    'about.value4.title': 'Sustainability',
    'about.value4.desc': 'We care for Egypt’s heritage and environment.',
    'about.closing': 'Join us and let’s create your dream Egyptian adventure!',
  },

};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
