
import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'es' | 'pt' | 'br';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations = {
  ar: {
    'nav.destinations': 'الوجهات',
    'nav.packages': 'الباقات',
    'nav.experiences': 'التجارب',
    'nav.tripbuilder': 'بناء الرحلة',
    'nav.about': 'من نحن',
    'nav.contact': 'تواصل معنا',
    'nav.blog': 'مدونة',
    'hero.title': 'اكتشف مصر كما لم تراها من قبل',
    'hero.subtitle': 'استمتع بروائع مصر الخالدة مع تجاربنا الفاخرة المختارة بعناية',
    'hero.cta': 'ابدأ رحلتك',
    'destinations.title': 'أفضل الوجهات',
    'destinations.subtitle': 'استكشف أجمل الأماكن في مصر',
    'destinations.seeAll': 'عرض كل الوجهات',
    'packages.title': 'الباقات المميزة',
    'packages.subtitle': 'رحلات مصممة بعناية لكل مسافر',
    'packages.viewAll': 'عرض جميع الباقات',
    'experiences.title': 'تجارب ثقافية',
    'experiences.subtitle': 'تجارب أصيلة مع التراث المصري',
    'experiences.exploreAll': 'استكشف كل التجارب',
    'why.title': 'لماذا مصر؟',
    'testimonials.title': 'قصص المسافرين',
    'newsletter.title': 'ابق على اطلاع',
    'newsletter.subtitle': 'احصل على نصائح وعروض حصرية',
    'newsletter.placeholder': 'أدخل بريدك الإلكتروني',
    'newsletter.subscribe': 'اشترك',
    // Package Details
    'package.loading': 'جاري تحميل تفاصيل الباقة...',
    'package.notfound': 'الباقة غير موجودة',
    'package.back': 'رجوع',
    'package.highlights': 'النقاط البارزة',
    'package.cancellationPolicyTitle': 'سياسة الإلغاء',
    'package.cancellationPolicy': 'يمكنك الإلغاء مجانًا حتى 24 ساعة قبل موعد الرحلة.',
    'package.bookNow': 'احجز الآن',
    'package.success': 'تم إرسال طلب الحجز بنجاح! سنقوم بالتواصل معك قريبًا.',
    'package.fullName': 'الاسم الكامل',
    'package.fullNamePlaceholder': 'اكتب اسمك الكامل',
    'package.email': 'البريد الإلكتروني',
    'package.emailPlaceholder': 'example@email.com',
    'package.phone': 'رقم الهاتف',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'تاريخ الرحلة',
    'package.datePlaceholder': 'اختر تاريخ الرحلة',
    'package.people': 'عدد الأشخاص',
    'package.peoplePlaceholder': 'اكتب عدد الأشخاص',
    'package.submit': 'إتمام الحجز',
    // Experiences Page
    'experiences.title': 'التجارب الثقافية',
    'experiences.subtitle': 'انغمس في الثقافة المصرية الأصيلة مع تجاربنا الفريدة',
    'experiences.notfound': 'لا توجد تجارب متاحة.',
    'error.loading': 'حدث خطأ أثناء التحميل',
    // Destination Details
    'destination.loading': 'جاري تحميل تفاصيل الوجهة...',
    'destination.notfound': 'الوجهة غير موجودة',
    'destination.back': 'رجوع',
    'destination.highlights': 'النقاط البارزة',
    // Experiences Details
    'experience.loading': 'جاري تحميل تفاصيل التجربة...',
    'experience.notfound': 'التجربة غير موجودة',
    'experience.back': 'رجوع',
    'experience.highlights': 'النقاط البارزة',
  },
  en: {
    'nav.destinations': 'Destinations',
    'nav.packages': 'Packages',
    'nav.experiences': 'Experiences',
    'nav.tripbuilder': 'Trip Builder',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'hero.title': 'Discover Egypt Like Never Before',
    'hero.subtitle': 'Immerse yourself in the timeless wonders of ancient Egypt with our curated luxury experiences',
    'hero.cta': 'Start Your Journey',
    'destinations.title': 'Top Destinations',
    'destinations.subtitle': 'Explore Egypt\'s most captivating locations',
    'destinations.seeAll': 'See All Destinations',
    'packages.title': 'Popular Packages',
    'packages.subtitle': 'Carefully crafted journeys for every traveler',
    'packages.viewAll': 'View All Packages',
    'experiences.title': 'Cultural Experiences',
    'experiences.subtitle': 'Authentic encounters with Egyptian heritage',
    'experiences.exploreAll': 'Explore All Experiences',
    'why.title': 'Why Choose Egypt?',
    'testimonials.title': 'Traveler Stories',
    'newsletter.title': 'Stay Updated',
    'newsletter.subtitle': 'Get exclusive travel insights and special offers',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.subscribe': 'Subscribe',
    // Package Details
    'package.loading': 'Loading package details...',
    'package.notfound': 'Package Not Found',
    'package.back': 'Back',
    'package.highlights': 'Highlights',
    'package.cancellationPolicyTitle': 'Cancellation Policy',
    'package.cancellationPolicy': 'You can cancel free of charge up to 24 hours before the trip.',
    'package.bookNow': 'Book Now',
    'package.success': 'Booking request sent successfully! We will contact you soon.',
    'package.fullName': 'Full Name',
    'package.fullNamePlaceholder': 'Enter your full name',
    'package.email': 'Email',
    'package.emailPlaceholder': 'example@email.com',
    'package.phone': 'Phone Number',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Trip Date',
    'package.datePlaceholder': 'Select trip date',
    'package.people': 'Number of People',
    'package.peoplePlaceholder': 'Enter number of people',
    'package.submit': 'Submit Booking',
    // Experiences Page
    'experiences.title': 'Cultural Experiences',
    'experiences.subtitle': 'Immerse yourself in authentic Egyptian culture with our unique experiences',
    'experiences.notfound': 'No experiences found.',
    'error.loading': 'Error loading experiences',
    // Destination Details
    'destination.loading': 'Loading destination details...',
    'destination.notfound': 'Destination Not Found',
    'destination.back': 'Back',
    'destination.highlights': 'Highlights',
    // Experiences Details
    'experience.loading': 'Loading experience details...',
    'experience.notfound': 'Experience Not Found',
    'experience.back': 'Back',
    'experience.highlights': 'Highlights',
  },
  es: {
    'nav.destinations': 'Destinos',
    'nav.packages': 'Paquetes',
    'nav.experiences': 'Experiencias',
    'nav.tripbuilder': 'Planificador',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.blog': 'Blog',
    'hero.title': 'Descubre Egipto Como Nunca Antes',
    'hero.subtitle': 'Sumérgete en las maravillas eternas del antiguo Egipto con nuestras experiencias de lujo',
    'hero.cta': 'Comienza Tu Viaje',
    'destinations.title': 'Principales Destinos',
    'destinations.subtitle': 'Explora los lugares más cautivadores de Egipto',
    'destinations.seeAll': 'Ver Todos los Destinos',
    'packages.title': 'Paquetes Populares',
    'packages.subtitle': 'Viajes cuidadosamente diseñados para cada viajero',
    'packages.viewAll': 'Ver Todos los Paquetes',
    'experiences.title': 'Experiencias Culturales',
    'experiences.subtitle': 'Encuentros auténticos con el patrimonio egipcio',
    'experiences.exploreAll': 'Explorar Todas las Experiencias',
    'why.title': '¿Por Qué Elegir Egipto?',
    'testimonials.title': 'Historias de Viajeros',
    'newsletter.title': 'Mantente Actualizado',
    'newsletter.subtitle': 'Recibe información exclusiva de viajes y ofertas especiales',
    'newsletter.placeholder': 'Ingresa tu email',
    'newsletter.subscribe': 'Suscribirse',
    // Package Details
    'package.loading': 'Cargando detalles del paquete...',
    'package.notfound': 'Paquete no encontrado',
    'package.back': 'Atrás',
    'package.highlights': 'Aspectos destacados',
    'package.cancellationPolicyTitle': 'Política de cancelación',
    'package.cancellationPolicy': 'Puedes cancelar gratis hasta 24 horas antes del viaje.',
    'package.bookNow': 'Reservar ahora',
    'package.success': '¡Solicitud de reserva enviada con éxito! Nos pondremos en contacto contigo pronto.',
    'package.fullName': 'Nombre completo',
    'package.fullNamePlaceholder': 'Introduce tu nombre completo',
    'package.email': 'Correo electrónico',
    'package.emailPlaceholder': 'example@email.com',
    'package.phone': 'Número de teléfono',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Fecha del viaje',
    'package.datePlaceholder': 'Selecciona la fecha del viaje',
    'package.people': 'Número de personas',
    'package.peoplePlaceholder': 'Introduce el número de personas',
    'package.submit': 'Enviar reserva',
    // Experiences Page
    'experiences.title': 'Experiencias culturales',
    'experiences.subtitle': 'Sumérgete en la cultura egipcia auténtica con nuestras experiencias únicas',
    'experiences.notfound': 'No se encontraron experiencias.',
    'error.loading': 'Error al cargar experiencias',
    // Destination Details
    'destination.loading': 'Cargando detalles del destino...',
    'destination.notfound': 'Destino no encontrado',
    'destination.back': 'Atrás',
    'destination.highlights': 'Aspectos destacados',
    // Experiences Details
    'experience.loading': 'Cargando detalles de la experiencia...',
    'experience.notfound': 'Experiencia no encontrada',
    'experience.back': 'Atrás',
    'experience.highlights': 'Aspectos destacados',
  },
  pt: {
    'nav.destinations': 'Destinos',
    'nav.packages': 'Pacotes',
    'nav.experiences': 'Experiências',
    'nav.tripbuilder': 'Planeador',
    'nav.about': 'Sobre',
    'nav.contact': 'Contacto',
    'nav.blog': 'Blog',
    'hero.title': 'Descubra o Egipto Como Nunca',
    'hero.subtitle': 'Mergulhe nas maravilhas eternas do antigo Egipto com as nossas experiências de luxo',
    'hero.cta': 'Inicie a Sua Jornada',
    'destinations.title': 'Principais Destinos',
    'destinations.subtitle': 'Explore os locais mais cativantes do Egipto',
    'destinations.seeAll': 'Ver Todos os Destinos',
    'packages.title': 'Pacotes Populares',
    'packages.subtitle': 'Viagens cuidadosamente criadas para cada viajante',
    'packages.viewAll': 'Ver Todos os Pacotes',
    'experiences.title': 'Experiências Culturais',
    'experiences.subtitle': 'Encontros autênticos com o património egipcio',
    'experiences.exploreAll': 'Explorar Todas as Experiências',
    'why.title': 'Porquê Escolher o Egipto?',
    'testimonials.title': 'Histórias de Viajantes',
    'newsletter.title': 'Mantenha-se Atualizado',
    'newsletter.subtitle': 'Receba informações exclusivas de viagem e ofertas especiais',
    'newsletter.placeholder': 'Digite o seu email',
    'newsletter.subscribe': 'Subscrever',
    // Package Details
    'package.loading': 'A carregar detalhes do pacote...',
    'package.notfound': 'Pacote não encontrado',
    'package.back': 'Voltar',
    'package.highlights': 'Destaques',
    'package.cancellationPolicyTitle': 'Política de cancelamento',
    'package.cancellationPolicy': 'Pode cancelar gratuitamente até 24 horas antes da viagem.',
    'package.bookNow': 'Reservar agora',
    'package.success': 'Pedido de reserva enviado com sucesso! Entraremos em contato em breve.',
    'package.fullName': 'Nome completo',
    'package.fullNamePlaceholder': 'Digite o seu nome completo',
    'package.email': 'Email',
    'package.emailPlaceholder': 'example@email.com',
    'package.phone': 'Número de telefone',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Data da viagem',
    'package.datePlaceholder': 'Selecione a data da viagem',
    'package.people': 'Número de pessoas',
    'package.peoplePlaceholder': 'Digite o número de pessoas',
    'package.submit': 'Enviar reserva',
  },
  br: {
    'nav.destinations': 'Destinos',
    'nav.packages': 'Pacotes',
    'nav.experiences': 'Experiências',
    'nav.tripbuilder': 'Planejador',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.blog': 'Blog',
    'hero.title': 'Descubra o Egito Como Nunca Antes',
    'hero.subtitle': 'Mergulhe nas maravilhas eternas do antigo Egito com nossas experiências de luxo',
    'hero.cta': 'Comece Sua Jornada',
    'destinations.title': 'Principais Destinos',
    'destinations.subtitle': 'Explore os locais mais cativantes do Egito',
    'destinations.seeAll': 'Ver Todos os Destinos',
    'packages.title': 'Pacotes Populares',
    'packages.subtitle': 'Viagens cuidadosamente criadas para cada viajante',
    'packages.viewAll': 'Ver Todos os Pacotes',
    'experiences.title': 'Experiências Culturais',
    'experiences.subtitle': 'Encontros autênticos com o patrimônio egípcio',
    'experiences.exploreAll': 'Explorar Todas as Experiências',
    'why.title': 'Por Que Escolher o Egito?',
    'testimonials.title': 'Histórias de Viajantes',
    'newsletter.title': 'Mantenha-se Atualizado',
    'newsletter.subtitle': 'Receba informações exclusivas de viagem e ofertas especiais',
    'newsletter.placeholder': 'Digite seu email',
    'newsletter.subscribe': 'Assinar',
    // Package Details
    'package.loading': 'Carregando detalhes do pacote...',
    'package.notfound': 'Pacote não encontrado',
    'package.back': 'Voltar',
    'package.highlights': 'Destaques',
    'package.cancellationPolicyTitle': 'Política de cancelamento',
    'package.cancellationPolicy': 'Você pode cancelar gratuitamente até 24 horas antes da viagem.',
    'package.bookNow': 'Reservar agora',
    'package.success': 'Pedido de reserva enviado com sucesso! Entraremos em contato em breve.',
    'package.fullName': 'Nome completo',
    'package.fullNamePlaceholder': 'Digite seu nome completo',
    'package.email': 'Email',
    'package.emailPlaceholder': 'example@email.com',
    'package.phone': 'Número de telefone',
    'package.phonePlaceholder': '0100xxxxxxx',
    'package.date': 'Data da viagem',
    'package.datePlaceholder': 'Selecione a data da viagem',
    'package.people': 'Número de pessoas',
    'package.peoplePlaceholder': 'Digite o número de pessoas',
    'package.submit': 'Enviar reserva',
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
